Repository CA-G12/PMS, pull requests merged in 2022-10, with the labels that each got.

#6 4-create database connection
  .vscode/settings.json
  server/database/config/connection.ts
Labels: Awaiting Review

#9 Add Fake Data
  client/package-lock.json
  package.json
  server/database/seeds/adminProduct.json
  server/database/seeds/pharmacy.json
  server/database/seeds/product.json
  server/database/seeds/productPharmacy.json
  server/database/seeds/productsRequest.json
  server/database/seeds/salesHistory.json
Labels: Awaiting Review

#7 Create Database Models
  server/models/adminProduct.ts
  server/models/pharmacy.ts
  server/models/product.ts
  server/models/productPharmacy.ts
  server/models/productsRequest.ts
  server/models/salesHistory.ts
Labels: Done

#11 10 database relations
  server/database/seeds/salesHistory.json
  server/models/adminProduct.ts
  server/models/index.ts
  server/models/pharmacy.ts
  server/models/product.ts
  server/models/productPharmacy.ts
  server/models/productsRequest.ts
  server/models/salesHistory.ts
Labels: Awaiting Review

#16 add authorized fun for user
  package-lock.json
  package.json
  server/middlewares/auth.ts
  server/middlewares/interfaces/UserRequest.ts
  server/middlewares/interfaces/index.ts
  server/utils/CustomError.ts
  server/utils/index.ts
  server/utils/verifyToken.ts
Labels: Awaiting Review, BACK-END

#20 8 build fake data in database
  .eslintrc.json
  package.json
  server/database/config/buildDb.ts
  server/database/config/connection.ts
  server/database/seeds/buildSeeds.ts
  server/database/seeds/index.ts
  server/database/seeds/pharmacy.json
  server/database/seeds/productPharmacy.json
  server/database/seeds/salesHistory.json
  server/models/adminProduct.ts
  server/models/index.ts
  server/models/pharmacy.ts
  server/models/product.ts
  server/models/productPharmacy.ts
  server/models/productsRequest.ts
  server/models/salesHistory.ts
Labels: Done

#26 15 auth route GET /auth
  server/controllers/authentication/auth.ts
  server/controllers/authentication/index.ts
  server/controllers/index.ts
  server/middlewares/auth.ts
  server/middlewares/index.ts
  server/routes/authentication/auth.ts
Labels: Awaiting Review, BACK-END

#34 create admin model
  client/src/index.tsx
  package.json
  server/database/seeds/admin.json
  server/database/seeds/buildSeeds.ts
  server/database/seeds/index.ts
  server/middlewares/adminAuth.ts
  server/models/admin.ts
  server/models/index.ts
Labels: Done

#31 28 logout router new
  server/controllers/authentication/index.ts
  server/controllers/authentication/logout.ts
  server/controllers/index.ts
  server/routes/authentication/logout.ts
Labels: Done, BACK-END

#35 17 auth middleware for admin
  server/middlewares/adminAuth.ts
Labels: Done

#45 39 admin requests request
  .eslintrc.json
  client/src/index.tsx
  jest.config.js
  package-lock.json
  package.json
  server/app.ts
  server/controllers/admin/index.ts
  server/controllers/admin/requestStatus.ts
  server/controllers/index.ts
  server/database/seeds/buildSeeds.ts
  server/queries/admin/index.ts
  server/queries/admin/requestStatus.ts
  server/queries/index.ts
  server/routes/admin/requestStatus.ts
  server/test/admin/requestStatus.test.ts
  server/test/index.test.js
  server/validation/requestStatusSchema.ts
Labels: Request-Change

#22 [POST] /auth/signup
  package.json
  server/app.ts
  server/controllers/authentication/signUp.ts
  server/middlewares/Error.ts
  server/middlewares/interfaces/index.ts
  server/middlewares/interfaces/payloadType.ts
  server/middlewares/interfaces/userData.ts
  server/models/pharmacy.ts
  server/queries/authentication/index.ts
  server/queries/authentication/login.ts
  server/queries/authentication/logout.ts
  server/queries/authentication/signUp.ts
  server/routes/authentication/signUp.ts
  server/test/admin/signup.test.ts
  server/utils/generateToken.ts
  server/utils/index.ts
  server/validation/signupSchema.ts
Labels: Done, BACK-END, Route

#44 [GET] admin statistics
  server/app.ts
  server/controllers/admin/index.ts
  server/controllers/admin/overview.ts
  server/controllers/index.ts
  server/database/seeds/pharmacy.json
  server/queries/admin/overview.ts
  server/routes/admin/allApplications.ts
  server/routes/admin/allPharmacies.ts
  server/routes/admin/allRequests.ts
  server/routes/admin/applicationStatus.ts
  server/routes/admin/index.ts
  server/routes/admin/overview.ts
  server/routes/admin/pharamcyStatus.ts
  server/routes/admin/productsStatistics.ts
  server/routes/admin/requestStatus.ts
  server/routes/adminRoutes.ts
  server/test/admin/overview.test.ts
Labels: Done, BACK-END, Route

#52 Pharmacy middleware
  server/controllers/authentication/signUp.ts
  server/middlewares/index.ts
  server/middlewares/pharmacyAuth.ts
Labels: Done, BACK-END

#27 18 auth login
  client/src/components/Button.tsx
  client/src/components/auth/Signup.tsx
  client/src/utils/ButtonComponentType.ts
  client/src/utils/index.tsx
  package-lock.json
  package.json
  server/app.ts
  server/controllers/admin/index.ts
  server/controllers/admin/overview.ts
  server/controllers/admin/requestStatus.ts
  server/controllers/authentication/index.ts
  server/controllers/authentication/login.ts
  server/controllers/authentication/signUp.ts
  server/controllers/index.ts
  server/database/config/connection.ts
  server/middlewares/Error.ts
  server/middlewares/adminAuth.ts
  server/middlewares/auth.ts
  server/middlewares/interfaces/UserRequest.ts
  server/middlewares/interfaces/adminType.ts
  server/middlewares/interfaces/index.ts
  server/models/admin.ts
  server/models/pharmacy.ts
  server/queries/admin/overview.ts
  server/queries/authentication/adminLogin.ts
  server/queries/authentication/index.ts
  server/queries/authentication/login.ts
  server/queries/index.ts
  server/routes/admin/index.ts
  server/routes/admin/requestStatus.ts
  server/routes/adminRoutes.ts
  server/routes/authentication/auth.ts
  server/routes/authentication/index.ts
  server/routes/authentication/login.ts
  server/routes/authentication/logout.ts
  server/routes/authentication/signUp.ts
  server/routes/index.ts
  server/test/admin/login.test.ts
  server/test/admin/overview.test.ts
  server/test/admin/requestStatus.test.ts
  server/test/admin/signup.test.ts
  server/utils/generateToken.ts
  server/validation/index.ts
  server/validation/loginSchema.ts
Labels: Done, BACK-END

#56 Adding dashboard layout
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/assets/logo.png
  client/src/components/NavBar.tsx
  client/src/components/drawer.tsx
  client/src/index.tsx
  client/src/pages/.gitkeep
  client/src/pages/Applications.tsx
  client/src/pages/DashboardLayout.tsx
  client/src/pages/Overview.tsx
  client/src/pages/Pharmacies.tsx
  client/src/pages/Products.tsx
  client/src/pages/Requests.tsx
  client/src/pages/index.tsx
Labels: Done, FRONT-END

#60 In Progress Component
  client/src/components/InProgressModal.tsx
  client/src/components/style.css
Labels: Done, FRONT-END

#53 create apllication card
  client/src/App.tsx
  client/src/components/InProgressModal.tsx
  client/src/components/NavBar.tsx
  client/src/components/admin/ApplicationCard.tsx
  client/src/components/drawer.tsx
  client/src/index.tsx
  client/src/pages/Applications.tsx
  client/src/pages/Overview.tsx
  client/src/pages/Pharmacies.tsx
  client/src/pages/Products.tsx
  client/src/pages/Requests.tsx
  client/src/pages/index.tsx
  package-lock.json
  server/controllers/admin/overview.ts
  server/controllers/authentication/signUp.ts
  server/middlewares/pharmacyAuth.ts
Labels: Done, FRONT-END

#43 Get Admin Pharmacies
  client/src/components/Button.tsx
  client/src/components/auth/Signup.tsx
  client/src/utils/ButtonComponentType.ts
  client/src/utils/index.tsx
  server/app.ts
  server/controllers/admin/allPharmacies.ts
  server/controllers/admin/index.ts
  server/controllers/admin/overview.ts
  server/controllers/admin/requestStatus.ts
  server/controllers/authentication/auth.ts
  server/controllers/authentication/index.ts
  server/controllers/authentication/login.ts
  server/controllers/authentication/signUp.ts
  server/controllers/index.ts
  server/middlewares/Error.ts
  server/middlewares/adminAuth.ts
  server/middlewares/auth.ts
  server/middlewares/customError.ts
  server/middlewares/index.ts
  server/middlewares/interfaces/UserRequest.ts
  server/middlewares/interfaces/index.ts
  server/middlewares/interfaces/pharmacyStatus.ts
  server/middlewares/pharmacyAuth.ts
  server/queries/admin/allPharmacies.ts
  server/queries/admin/index.ts
  server/queries/admin/overview.ts
  server/queries/index.ts
  server/routes/admin/index.ts
  server/routes/admin/requestStatus.ts
  server/routes/adminRoutes.ts
  server/routes/authRoutes.ts
  server/routes/authentication/auth.ts
  server/routes/authentication/index.ts
  server/routes/authentication/login.ts
  server/routes/authentication/logout.ts
  server/routes/authentication/signUp.ts
  server/routes/index.ts
  server/test/admin/getAllPharmacies.test.ts
  server/validation/index.ts
  server/validation/pharmacyStatusSchema.ts
Labels: Done, BACK-END, Route

#65 logout button
  client/src/components/NavBar.tsx
  server/routes/authRoutes.ts
Labels: Done, FRONT-END

#30 19 login page
  client/src/components/Button.tsx
  client/src/components/NavBar.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/login.tsx
  client/src/utils/ButtonComponentType.ts
  client/src/utils/index.tsx
  server/controllers/admin/allPharmacies.ts
  server/controllers/admin/index.ts
  server/controllers/admin/overview.ts
  server/controllers/authentication/index.ts
  server/controllers/index.ts
  server/middlewares/Error.ts
  server/middlewares/adminAuth.ts
  server/middlewares/auth.ts
  server/middlewares/index.ts
  server/middlewares/interfaces/UserRequest.ts
  server/middlewares/pharmacyAuth.ts
  server/queries/admin/allPharmacies.ts
  server/queries/admin/index.ts
  server/queries/admin/overview.ts
  server/routes/authRoutes.ts
  server/routes/index.ts
  server/test/admin/getAllPharmacies.test.ts
  server/test/admin/overview.test.ts
  server/test/admin/requestStatus.test.ts
  server/validation/index.ts
  server/validation/pharmacyStatusSchema.ts
Labels: Done, FRONT-END

#66 Auth context for authorization
  client/src/components/Button.tsx
  client/src/context/authContext.tsx
  client/src/utils/UserContext.ts
  client/src/utils/UserData.ts
  client/src/utils/index.tsx
  server/controllers/admin/allPharmacies.ts
Labels: Awaiting Review, FRONT-END

#67 48 admin overview and statistics
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/assets/chart1.png
  client/src/components/Button.tsx
  client/src/components/InProgressModal.tsx
  client/src/components/InputForm.tsx
  client/src/components/NavBar.tsx
  client/src/components/admin/ApplicationCard.tsx
  client/src/components/admin/BoxComponent.tsx
  client/src/components/admin/ChartComponent.tsx
  client/src/components/admin/ListItemComponent.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/login.tsx
  client/src/components/drawer.tsx
  client/src/context/authContext.tsx
  client/src/index.tsx
  client/src/pages/Applications.tsx
  client/src/pages/DashboardLayout.tsx
  client/src/pages/Overview.tsx
  client/src/pages/Pharmacies.tsx
  client/src/pages/Products.tsx
  client/src/pages/Requests.tsx
  client/src/pages/index.tsx
  client/src/utils/UserContext.ts
  client/src/utils/index.tsx
  server/controllers/admin/overview.ts
  server/queries/admin/overview.ts
Labels: Done, FRONT-END

#40 create admin/requests router
  client/src/App.tsx
  client/src/components/Button.tsx
  client/src/components/InProgressModal.tsx
  client/src/components/InputForm.tsx
  client/src/components/NavBar.tsx
  client/src/components/admin/ApplicationCard.tsx
  client/src/components/admin/BoxComponent.tsx
  client/src/components/admin/ChartComponent.tsx
  client/src/components/admin/ListItemComponent.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/login.tsx
  client/src/components/drawer.tsx
  client/src/context/authContext.tsx
  client/src/index.tsx
  client/src/pages/Applications.tsx
  client/src/pages/DashboardLayout.tsx
  client/src/pages/Overview.tsx
  client/src/pages/Pharmacies.tsx
  client/src/pages/Products.tsx
  client/src/pages/Requests.tsx
  client/src/pages/index.tsx
  client/src/utils/UserContext.ts
  client/src/utils/index.tsx
  server/controllers/admin/allRequests.ts
  server/controllers/admin/index.ts
  server/controllers/admin/overview.ts
  server/controllers/authentication/signUp.ts
  server/controllers/index.ts
  server/models/index.ts
  server/queries/admin/allRequests.ts
  server/queries/admin/index.ts
  server/queries/admin/overview.ts
  server/queries/index.ts
  server/routes/adminRoutes.ts
  server/routes/authentication/signUp.ts
  server/test/admin/allAdminProduct.test.ts
  server/test/admin/allRequests.test.ts
  server/test/admin/getAllPharmacies.test.ts
Labels: Done, BACK-END

#58 54 admin applications section
  client/.eslintrc.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/assets/empty.webp
  client/src/components/admin/ApplicationCard.tsx
  client/src/components/admin/ApplicationSection.tsx
  client/src/pages/DashboardLayout.tsx
  client/tsconfig.json
  server/test/admin/getAllPharmacies.test.ts
  server/test/admin/signup.test.ts
Labels: Done, FRONT-END

#69 Fix types and eslint problems
  client/src/context/authContext.tsx
  client/src/pages/Overview.tsx
Labels: Awaiting Review, FRONT-END

#62 create the table put wait for data
  client/src/assets/image31.png
  client/src/pages/AdminProductTable/AdminAllProducts.tsx
  client/src/pages/Overview.tsx
  client/src/pages/Products.tsx
Labels: Done, FRONT-END

#75 74 get pharmasies
  server/controllers/index.ts
  server/controllers/users/index.ts
  server/controllers/users/pharmacies.ts
  server/queries/index.ts
  server/queries/users/index.ts
  server/queries/users/pharmacies.ts
  server/routes/index.ts
  server/routes/users.ts
  server/test/admin/signup.test.ts
  server/test/users/pharmacies.test.ts
Labels: Awaiting Review, BACK-END, Route

#78 77 get pharmacy pharmacy
  server/controllers/index.ts
  server/controllers/pharamcies/index.ts
  server/controllers/pharamcies/pharmacyOverview.ts
  server/queries/index.ts
  server/queries/pharamcies/index.ts
  server/queries/pharamcies/pharmacyOverview.ts
  server/routes/index.ts
  server/routes/pharmacies.ts
  server/test/pharmacies/pharmacy.test.ts
Labels: Done, BACK-END, Route

#79 72 get pharmacy requests
  server/controllers/index.ts
  server/controllers/pharamcies/index.ts
  server/controllers/pharamcies/pharamcyRequests.ts
  server/middlewares/pharmacyAuth.ts
  server/queries/index.ts
  server/queries/pharamcies/index.ts
  server/queries/pharamcies/pharamcyRequests.ts
  server/routes/pharamcies/pharamcyRequests.ts
  server/routes/pharmacies.ts
  server/test/admin/pharmacyRequests.test.ts
  server/test/users/pharmacies.test.ts
  server/validation/IdPageSchema.ts
Labels: Done, BACK-END

#85 70-get products with filtering option
  server/controllers/pharamcies/index.ts
  server/controllers/pharamcies/pharmacyProducts.ts
  server/models/index.ts
  server/queries/pharamcies/index.ts
  server/queries/pharamcies/pharmacyProducts.ts
  server/routes/pharamcies/index.ts
  server/routes/pharmacies.ts
  server/test/admin/allProducts.test.ts
  server/test/admin/putStatus.test.ts
  server/validation/index.ts
  server/validation/nameNumberValidator.ts
Labels: Done, BACK-END

#86 Post Pharmacy Sales
  server/controllers/pharamcies/addSales.ts
  server/controllers/pharamcies/index.ts
  server/controllers/users/pharmacies.ts
  server/queries/pharamcies/addSales.ts
  server/queries/pharamcies/index.ts
  server/routes/pharmacies.ts
  server/test/admin/addSalesHistory.test.ts
  server/validation/IdValidator.ts
Labels: Done, BACK-END

#88 Get pharmacy Statistics
  server/controllers/pharamcies/index.ts
  server/controllers/pharamcies/pharmacyStatistics.ts
  server/queries/pharamcies/index.ts
  server/queries/pharamcies/pharmacyStatistics.ts
  server/routes/pharamcies/index.ts
  server/routes/pharmacies.ts
  server/test/admin/pharamcyStatistics.test.ts
  server/validation/index.ts
  server/validation/pharmacyIdSchema.ts
Labels: Done, BACK-END

#104 Header Component in Landing Page
  client/src/assets/landing.png
  client/src/pages/LandingPages/Header.tsx
  client/src/pages/LandingPages/style.css
Labels: Awaiting Review, FRONT-END

#114 Pharmacy Profile Layout
  client/src/App.tsx
  client/src/assets/profile.jpg
  client/src/pages/PharmacyProfile/ActiveRequests.tsx
  client/src/pages/PharmacyProfile/PharmacyProducts.tsx
  client/src/pages/PharmacyProfile/ProfileLayout.tsx
  client/src/pages/PharmacyProfile/ProfileOverview.tsx
  client/src/pages/PharmacyProfile/SalesHistory.tsx
  client/src/pages/PharmacyProfile/index.tsx
  client/src/pages/PharmacyProfile/profile.css
  client/src/utils/PharmacyData.ts
  server/controllers/pharamcies/index.ts
  server/queries/pharamcies/index.ts
  server/routes/pharamcies/index.ts
  server/routes/pharmacies.ts
Labels: Awaiting Review, FRONT-END
