Repository CA-G12/PMS, pull requests merged in 2022-11, with the labels that each got.

#84 83 post pharmacy requests
  server/controllers/index.ts
  server/controllers/pharamcies/addRequests.ts
  server/controllers/pharamcies/index.ts
  server/middlewares/pharmacyAuth.ts
  server/models/productsRequest.ts
  server/queries/index.ts
  server/queries/pharamcies/addRequests.ts
  server/queries/pharamcies/index.ts
  server/routes/pharmacies.ts
  server/test/pharamcies/addRequests.test.ts
Labels: Awaiting Review, BACK-END, Route

#99 create the queries and the controllers
  server/controllers/index.ts
  server/controllers/pharamcies/editRequests.ts
  server/controllers/pharamcies/index.ts
  server/queries/index.ts
  server/queries/pharamcies/eidtRequestsQuery.ts
  server/queries/pharamcies/index.ts
  server/routes/index.ts
  server/routes/pharmaciesRouter.ts
  server/test/pharmacy/editRequests.test.ts
Labels: Awaiting Review, BACK-END

#106 105 get products in stock
  client/src/components/pharmacy/Statistics.tsx
  server/controllers/index.ts
  server/controllers/pharamcies/index.ts
  server/controllers/pharamcies/productsInStock.ts
  server/models/index.ts
  server/queries/index.ts
  server/queries/pharamcies/index.ts
  server/queries/pharamcies/productsInStock.ts
  server/routes/index.ts
  server/routes/pharmaciesRouter.ts
  server/test/admin/allProducts.test.ts
  server/test/pharamcies/productsInStock.test.ts
  server/test/pharmacy/editRequests.test.ts
Labels: Done, BACK-END, Route

#101 get one product
  server/controllers/index.ts
  server/controllers/pharamcies/index.ts
  server/controllers/pharamcies/oneProductId.ts
  server/queries/index.ts
  server/queries/pharamcies/getOneProductId.ts
  server/queries/pharamcies/index.ts
  server/routes/pharmaciesRouter.ts
  server/test/pharmasy/getProductById.test.ts
Labels: Awaiting Review, BACK-END

#115 112 pharmasies page component
  client/src/App.tsx
  client/src/pages/AllPharmacies.tsx
  client/src/pages/index.tsx
  server/database/seeds/pharmacy.json
Labels: Done, FRONT-END

#124 create pharmacy profile products component
  client/src/App.tsx
  client/src/components/FilterComponent.tsx
  client/src/components/ProductCard.tsx
  client/src/pages/PharmacyProfile/PharmacyProducts.tsx
  server/controllers/index.ts
  server/controllers/pharamcies/pharmacyProducts.ts
  server/queries/pharamcies/pharmacyProducts.ts
  server/routes/pharmaciesRouter.ts
  server/routes/users.ts
Labels: Done, FRONT-END

#57 create the header for the table
  client/package-lock.json
  client/package.json
  client/public/img/image31.png
  client/public/index.html
  client/src/pages/AllAdminPharmasis/AdminAllPharmasis.tsx
  client/src/pages/AllAdminPharmasis/Extra/Options.tsx
  client/src/pages/AllAdminPharmasis/Extra/Search.tsx
  client/src/pages/AllAdminPharmasis/Extra/style.css
  client/src/pages/AllAdminPharmasis/style.css
  client/src/pages/Overview.tsx
  client/src/pages/Pharmacies.tsx
Labels: Done, FRONT-END

#116 create products page component
  client/src/App.tsx
  client/src/pages/AllProducts.tsx
  client/src/pages/Overview.tsx
  client/src/pages/index.tsx
Labels: Done, FRONT-END

#129 Fix and update style
  client/public/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/assets/.gitkeep
  client/src/assets/key1.png
  client/src/assets/key2.png
  client/src/components/Extra/Options.tsx
  client/src/components/Extra/index.tsx
  client/src/components/Extra/style.css
  client/src/components/Landing/Footer.tsx
  client/src/components/Landing/Header.tsx
  client/src/components/Landing/KeyBenefits.tsx
  client/src/components/Landing/style.css
  client/src/components/NavBar.tsx
  client/src/components/NavBar/Navbar.css
  client/src/components/NavBar/Navbar.tsx
  client/src/components/admin/ApplicationCard.tsx
  client/src/components/admin/BoxComponent.tsx
  client/src/components/admin/allRequests.tsx
  client/src/components/drawer.tsx
  client/src/components/index.tsx
  client/src/components/pharmacy/info.css
  client/src/components/style.css
  client/src/pages/AdminDashboard/AdminAllPharmasis.tsx
  client/src/pages/AdminDashboard/Applications.tsx
  client/src/pages/AdminDashboard/DashboardLayout.tsx
  client/src/pages/AdminDashboard/Overview.tsx
  client/src/pages/AdminDashboard/Pharmacies.tsx
  client/src/pages/AdminDashboard/Products.tsx
  client/src/pages/AdminDashboard/Requests.tsx
  client/src/pages/AdminDashboard/dashboard.css
  client/src/pages/AdminDashboard/index.tsx
  client/src/pages/AdminProductTable/AdminAllProducts.tsx
  client/src/pages/AllAdminPharmasis/AdminAllPharmasis.tsx
  client/src/pages/AllAdminPharmasis/Extra/Options.tsx
  client/src/pages/AllAdminPharmasis/Extra/Search.tsx
  client/src/pages/AllAdminPharmasis/Extra/style.css
  client/src/pages/AllAdminPharmasis/style.css
  client/src/pages/Applications.tsx
  client/src/pages/LandingPages/Home.tsx
  client/src/pages/PharmacyProfile/ProfileLayout.tsx
  client/src/pages/PharmacyProfile/profile.css
  client/src/pages/Products.tsx
  client/src/pages/Requests.tsx
  client/src/pages/dashboard.css
  server/controllers/pharamcies/index.ts
  server/database/seeds/pharmacy.json
  server/routes/pharmaciesRouter.ts
Labels: Awaiting Review, FRONT-END

#127 [Frontend , Backend]edit querie and front page
  client/src/App.tsx
  client/src/pages/PharmacyProfile/PharmacyProfileRequests.tsx
  client/src/pages/PharmacyProfile/ProfileLayout.tsx
  client/src/pages/PharmacyProfile/SalesHistory.tsx
  server/controllers/pharamcies/salesHistory.ts
  server/queries/pharamcies/salesHistory.ts
  server/routes/pharmaciesRouter.ts
  server/test/pharamcies/salesHistory.test.ts
Labels: Awaiting Review, FRONT-END, BACK-END

#135 fix some bugs
  client/src/App.tsx
  client/src/components/NavBar/Navbar.tsx
  client/src/components/NavBar/PharmacyNavbar.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/login.tsx
  client/src/context/authContext.tsx
  server/controllers/authentication/login.ts
  server/controllers/authentication/signUp.ts
Labels: Awaiting Review

#137 Product popup component
  client/src/App.tsx
  client/src/components/ProductCard.tsx
  client/src/pages/AllProducts.tsx
  client/src/pages/PharmacyProfile/PharmacyProducts.tsx
Labels: Done, FRONT-END

#131 128# add sale popoup
  client/src/assets/image45.png
  client/src/components/pharmacy/AddSalesPopup.tsx
  client/src/pages/PharmacyProfile/SalesHistory.tsx
  server/controllers/pharamcies/addSales.ts
  server/models/index.ts
  server/queries/pharamcies/addSales.ts
  server/queries/pharamcies/salesHistory.ts
  server/routes/pharmaciesRouter.ts
Labels: Awaiting Review, FRONT-END

#133 Fix, update style and add routes
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/FilterComponent.tsx
  client/src/components/InputForm.tsx
  client/src/components/Landing/Footer.tsx
  client/src/components/Landing/Header.tsx
  client/src/components/Landing/KeyBenefits.tsx
  client/src/components/Landing/style.css
  client/src/components/NavBar.tsx
  client/src/components/NavBar/Navbar.css
  client/src/components/NavBar/Navbar.tsx
  client/src/components/NavBar/PharmacyNavbar.tsx
  client/src/components/PharmacyCard.tsx
  client/src/components/ProductCard.tsx
  client/src/components/ProtectedRoutes.tsx
  client/src/components/admin/BoxComponent.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/login.tsx
  client/src/components/drawer.tsx
  client/src/components/pharmacy/GeneralInfo.tsx
  client/src/components/pharmacy/MostSearchedPharmaciesSection.tsx
  client/src/components/pharmacy/Statistics.tsx
  client/src/components/pharmacy/info.css
  client/src/components/style.css
  client/src/context/authContext.tsx
  client/src/pages/AdminDashboard/AdminAllPharmasis.tsx
  client/src/pages/AdminDashboard/Applications.tsx
  client/src/pages/AdminDashboard/Pharmacies.tsx
  client/src/pages/AdminDashboard/Products.tsx
  client/src/pages/AdminDashboard/Requests.tsx
  client/src/pages/AdminDashboard/dashboard.css
  client/src/pages/AllPharmacies.tsx
  client/src/pages/AllProducts.tsx
  client/src/pages/LandingPages/Home.tsx
  client/src/pages/PharmacyProfile/PharmacyProducts.tsx
  client/src/pages/PharmacyProfile/PharmacyProfileRequests.tsx
  client/src/pages/PharmacyProfile/ProfileLayout.tsx
  client/src/pages/PharmacyProfile/SalesHistory.tsx
  client/src/pages/PharmacyProfile/profile.css
  server/database/seeds/pharmacy.json
  server/database/seeds/productPharmacy.json
  server/queries/admin/allPharmacies.ts
  server/queries/users/pharmacies.ts
  server/routes/pharmaciesRouter.ts
  server/test/admin/allRequests.test.ts
  server/test/admin/getAllPharmacies.test.ts
  server/test/pharamcies/pharmacies.test.ts
  server/test/pharamcies/pharmacy.test.ts
  server/test/pharamcies/productsInStock.test.ts
  server/test/pharamcies/salesHistory.test.ts
  server/test/pharmasy/getProductById.test.ts
  server/validation/pharmacyStatus.ts
Labels: Awaiting Review, FRONT-END

#140 139 deploy heroku
  .gitignore
  client/.eslintrc.json
  client/package.json
  client/src/components/auth/login.tsx
  client/tsconfig.json
  package.json
  server/database/config/connection.ts
  tsconfig.json
Labels: Awaiting Review

#81 update the backend signup to get status
  client/src/assets/Loading-pana 1.png
  client/src/components/YourApplicationIsInReview.tsx
  server/controllers/authentication/login.ts
  server/controllers/authentication/signUp.ts
  server/controllers/index.ts
  server/middlewares/checkStatus.ts
  server/middlewares/index.ts
  server/middlewares/interfaces/payloadType.ts
  server/middlewares/pharmacyAuth.ts
Labels: in-progress, FRONT-END, BACK-END

#145 handling pending pharmacy
  client/src/App.tsx
  client/src/components/Landing/style.css
  client/src/components/ProtectedRoutes.tsx
  client/src/components/YourApplicationIsInReview.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/login.tsx
  client/src/context/authContext.tsx
  server/controllers/authentication/signUp.ts
  server/middlewares/checkStatus.ts
  server/middlewares/pharmacyAuth.ts
Labels: Done

#142 create Pagination for Admin Products and fix some css
  client/src/components/ProductCard.tsx
  client/src/components/auth/login.tsx
  client/src/components/pharmacy/GeneralInfo.tsx
  client/src/components/pharmacy/Statistics.tsx
  client/src/components/pharmacy/pharmacyFilter.tsx
  client/src/pages/AdminDashboard/AdminAllPharmasis.tsx
  client/src/pages/AdminDashboard/Applications.tsx
  client/src/pages/AdminDashboard/Products.tsx
  client/src/pages/AdminDashboard/Requests.tsx
  client/src/pages/AllPharmacies.tsx
  client/src/pages/AllProducts.tsx
  client/src/pages/PharmacyProfile/PharmacyProducts.tsx
  server/controllers/admin/allAdminProducts.ts
  server/controllers/authentication/login.ts
  server/controllers/index.ts
  server/controllers/pharamcies/addSales.ts
  server/index.ts
  server/middlewares/index.ts
  server/middlewares/interfaces/payloadType.ts
  server/middlewares/pharmacyAuth.ts
  server/queries/admin/allAdminProducts.ts
  server/queries/admin/allRequests.ts
  server/validation/pharmacyStatus.ts
Labels: Awaiting Review, Done, FRONT-END

#146 fix some bugs
  client/src/pages/AdminDashboard/AdminAllPharmasis.tsx
  client/src/pages/AdminDashboard/Pharmacies.tsx
  server/queries/admin/allPharmacies.ts
  server/queries/pharamcies/salesHistory.ts
Labels: Done, FRONT-END, BACK-END

#147 Fix Bugs
  client/src/assets/no-data.png
  client/src/components/Extra/style.css
  client/src/components/Landing/style.css
  client/src/components/NavBar/Navbar.css
  client/src/components/NavBar/Navbar.tsx
  client/src/components/pharmacy/AddRequest.tsx
  client/src/components/style.css
  client/src/pages/AdminDashboard/Applications.tsx
  client/src/pages/AllPharmacies.tsx
  client/src/pages/AllProducts.tsx
  client/src/pages/PharmacyProfile/PharmacyProducts.tsx
  client/src/pages/PharmacyProfile/PharmacyProfileRequests.tsx
  client/src/pages/PharmacyProfile/ProfileLayout.tsx
  client/src/pages/PharmacyProfile/SalesHistory.tsx
  client/src/pages/PharmacyProfile/profile.css
  server/controllers/admin/applicationStatus.ts
  server/controllers/admin/index.ts
  server/controllers/index.ts
  server/controllers/pharamcies/getProducts.ts
  server/controllers/pharamcies/index.ts
  server/database/config/connection.ts
  server/queries/admin/allPharmacies.ts
  server/queries/admin/applicationUpdate.ts
  server/queries/admin/index.ts
  server/queries/index.ts
  server/queries/pharamcies/getProductsQuery.ts
  server/queries/pharamcies/index.ts
  server/routes/adminRoutes.ts
  server/routes/pharmaciesRouter.ts
  server/test/admin/allAdminProduct.test.ts
  server/validation/applicationSchema.ts
  server/validation/index.ts
Labels: Done, FRONT-END, BACK-END

#150 FIx style and deploy bugs
  client/src/App.css
  client/src/components/Button.tsx
  client/src/components/Landing/Footer.tsx
  client/src/components/Landing/Header.tsx
  client/src/components/Landing/KeyBenefits.tsx
  client/src/components/Landing/style.css
  client/src/components/NavBar/Navbar.css
  client/src/components/NavBar/Navbar.tsx
  client/src/components/drawer.tsx
  client/src/components/pharmacy/Statistics.tsx
  client/src/components/style.css
  client/src/pages/AdminDashboard/DashboardLayout.tsx
  client/src/pages/AdminDashboard/Overview.tsx
  client/src/pages/AdminDashboard/dashboard.css
  client/src/pages/PharmacyProfile/PharmacyProfileRequests.tsx
  client/src/pages/PharmacyProfile/SalesHistory.tsx
  server/app.ts
Labels: Done, FRONT-END, BACK-END

#151 Fix bugs
  client/public/index.html
  client/src/components/FilterComponent.tsx
  client/src/components/NavBar/Navbar.css
  client/src/components/NavBar/Navbar.tsx
  client/src/components/auth/Signup.tsx
  client/src/components/auth/login.tsx
  client/src/components/pharmacy/AddRequest.tsx
  client/src/components/pharmacy/AddSalesPopup.tsx
  client/src/components/pharmacy/GeneralInfo.tsx
  client/src/pages/AdminDashboard/dashboard.css
  client/src/pages/AllPharmacies.tsx
  client/src/pages/AllProducts.tsx
  client/src/pages/PharmacyProfile/PharmacyProducts.tsx
  client/src/pages/PharmacyProfile/PharmacyProfileRequests.tsx
  client/src/pages/PharmacyProfile/ProfileLayout.tsx
  client/src/pages/PharmacyProfile/SalesHistory.tsx
  client/src/pages/PharmacyProfile/profile.css
  client/src/utils/ScrollToTop.tsx
  server/controllers/pharamcies/addRequests.ts
  server/models/index.ts
  server/queries/pharamcies/pharamcyRequests.ts
  server/routes/pharmaciesRouter.ts
Labels: FRONT-END, BACK-END
